wget https://raw.githubusercontent.com/lipis/flag-icon-css/master/flags/4x3/be.svg
wget https://raw.githubusercontent.com/lipis/flag-icon-css/master/flags/4x3/bg.svg
wget https://raw.githubusercontent.com/lipis/flag-icon-css/master/flags/4x3/cz.svg
wget https://raw.githubusercontent.com/lipis/flag-icon-css/master/flags/4x3/dk.svg
wget https://raw.githubusercontent.com/lipis/flag-icon-css/master/flags/4x3/de.svg
wget https://raw.githubusercontent.com/lipis/flag-icon-css/master/flags/4x3/ee.svg
wget https://raw.githubusercontent.com/lipis/flag-icon-css/master/flags/4x3/ie.svg
wget https://raw.githubusercontent.com/lipis/flag-icon-css/master/flags/4x3/el.svg
wget https://raw.githubusercontent.com/lipis/flag-icon-css/master/flags/4x3/es.svg
wget https://raw.githubusercontent.com/lipis/flag-icon-css/master/flags/4x3/fr.svg
wget https://raw.githubusercontent.com/lipis/flag-icon-css/master/flags/4x3/hr.svg
wget https://raw.githubusercontent.com/lipis/flag-icon-css/master/flags/4x3/it.svg
wget https://raw.githubusercontent.com/lipis/flag-icon-css/master/flags/4x3/cy.svg
wget https://raw.githubusercontent.com/lipis/flag-icon-css/master/flags/4x3/lv.svg
wget https://raw.githubusercontent.com/lipis/flag-icon-css/master/flags/4x3/lt.svg
wget https://raw.githubusercontent.com/lipis/flag-icon-css/master/flags/4x3/lu.svg
wget https://raw.githubusercontent.com/lipis/flag-icon-css/master/flags/4x3/hu.svg
wget https://raw.githubusercontent.com/lipis/flag-icon-css/master/flags/4x3/mt.svg
wget https://raw.githubusercontent.com/lipis/flag-icon-css/master/flags/4x3/nl.svg
wget https://raw.githubusercontent.com/lipis/flag-icon-css/master/flags/4x3/at.svg
wget https://raw.githubusercontent.com/lipis/flag-icon-css/master/flags/4x3/pl.svg
wget https://raw.githubusercontent.com/lipis/flag-icon-css/master/flags/4x3/pt.svg
wget https://raw.githubusercontent.com/lipis/flag-icon-css/master/flags/4x3/ro.svg
wget https://raw.githubusercontent.com/lipis/flag-icon-css/master/flags/4x3/si.svg
wget https://raw.githubusercontent.com/lipis/flag-icon-css/master/flags/4x3/sk.svg
wget https://raw.githubusercontent.com/lipis/flag-icon-css/master/flags/4x3/fi.svg
wget https://raw.githubusercontent.com/lipis/flag-icon-css/master/flags/4x3/se.svg
wget https://raw.githubusercontent.com/lipis/flag-icon-css/master/flags/4x3/uk.svg
